apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: mysql-secrets-provider
  namespace: prod
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "prod/mysql/credentials"
        objectType: "secretsmanager"
        jmesPath:
          - path: "MYSQL_ROOT_PASSWORD"
            objectAlias: "MYSQL_ROOT_PASSWORD"
          - path: "MYSQL_DATABASE"
            objectAlias: "MYSQL_DATABASE"
          - path: "JWT_SECRET"
            objectAlias: "JWT_SECRET"
  secretObjects:
  - secretName: mysql-secret-from-aws
    type: Opaque
    data:
    - objectName: "MYSQL_ROOT_PASSWORD"
      key: "MYSQL_ROOT_PASSWORD"
    - objectName: "MYSQL_DATABASE"
      key: "MYSQL_DATABASE"
    - objectName: "JWT_SECRET"
      key: "JWT_SECRET"